---
title: srflmr - draft
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
site: srflmr
keywords: isrofil, srflmr, blog, site, draft
description: srflmr - draft
lang: en-US
repo: 
google_verify: XXX
google_analytics: UA-XXXXXXXX-00
discus-identifier: XXX
author:
  name: srflmr-draft
  bio: <a href="https://blog.srflmr.my.id"> srflmr blog </a> <br> /#uncencored-version
    of <br> <a href="https://srflmr.my.id"> /#srflmr-project </a>
  picture: assets/images/profile.png
  twitter: srflmr
  instagram: srflmr
url: https://draft.srflmr.my.id
baseurl: ''
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
- ".jekyll-cache"
- ".obsidian"
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- CONTRIBUTING.md
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-relative-links
paginate: 10
paginate_path: "/page/:num"
relative_links:
  enabled: true
  collections: false
