# Site settings
site: srflmr
title: srflmr - draft
keywords: isrofil, srflmr, blog, site, draft
description: >-
  srflmr - draft
lang: en-US
timezone:  UTC
repo:  # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: srflmr-draft
  bio: Sebuah blog biasa <br>
      /#uncencored-version of <a href="https://blog.srflmr.my.id"> srflmr blog </a> <br> 
      <a href="https://srflmr.my.id"> /#srflmr-project </a>
  picture: assets/images/profile.png 
  #github: onepase # github username
  twitter: srflmr # twitter username
  #facebook: onepase # facebook username
  instagram: srflmr # instagram username
  #youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  #linkedin: hakantorun # linkedin username
  #email: your-email@email.com # email adress


# URL settings
url: "https://draft-srflmr.netlify.app" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 10
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
